services:
  backend:
    image: cosc-310-project-backend:latest
    container_name: cosc-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - cosc

  frontend:
    image: cosc-310-project-frontend:latest
    container_name: cosc-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - cosc

networks:
  cosc:
    driver: bridge
